### ISSUE TITLE
BUG: artisanal typings require @uirouter/core when it's not a dependency of the project

### ISSUE THREAD

**Issue by tommck** [ui-router/visualizer#111]
Your new typings break compiles with strict typing.

`node_modules/@uirouter/visualizer/artisinal.typings.d.ts(1,55): error TS2307: Cannot find module '@uirouter/core'.`

**Comment by christopherthielen** [comment]
`@uirouter/core` is a `peerDependency` of the visualizer.  The rest of the uirouter projects are migrating towards leveraging `peerDependencies` as well.
