### ISSUE TITLE
Compatibility with D3 v4 

### ISSUE THREAD

**Issue by kshade2001** [ui-router/visualizer#13]
Is it possible to change the code to use an isolated D3 scope so later versions of D3 can be used in the application without affecting the visualizer.

At the moment if you are using a later version of D3 in your project you can't use the visualizer as it loads d3 into the global scope.

**Comment by christopherthielen** [comment]
Original bundle size using D3 version 3:
<img width="925" alt="screen shot 2017-01-25 at 9 01 16 pm" src="https://cloud.githubusercontent.com/assets/2053478/22338614/6e15ab0c-e3ad-11e6-8d6f-b022358a67cf.png">

**Comment by christopherthielen** [comment]
New bundle size using (modular) D3 version 4.x:
<img width="923" alt="screen shot 2017-01-25 at 9 01 38 pm" src="https://cloud.githubusercontent.com/assets/2053478/22338634/78bef7de-e3ad-11e6-84c5-9553ab941f44.png">
