### ISSUE TITLE
Is there a way to turn the visualizer off?

### ISSUE THREAD

**Issue by jziggas** [ui-router/visualizer#14]

**Comment by christopherthielen** [comment]
There is not currently a way to turn off the visualizer (if it has been turned on).

You could probably remove the element from the DOM, but I'm not sure if that works without side effects or not.

**Comment by christopherthielen** [comment]
You can now call `.dispose()` method on the plugin.

```
let plugin = router.plugin(Visualizer)

... 

plugin.dispose();
```
