### ISSUE TITLE
Visualizer for Sticky and DSR states ?

### ISSUE THREAD

**Issue by sdev-maxime** [ui-router/visualizer#281]
Hi,
I use the lastest @ui-router/visualizer with sticky and dsr states, but I've seen visualizer like this [this](http://christopherthielen.github.io/ui-router-extras/example/sticky/index.html#/inv/stores) on a previous versions, which contain details about sticky and dsr behavior.
Problem is with multiple try, I don't get the previous visualizer working. And it could be very helpfull ^^.
Is exist a way to make that visualizer with @ui-router ? or this need to be develop ?

Thx.

**Comment by christopherthielen** [comment]
I added support for a custom `label` function in https://github.com/ui-router/visualizer/releases/tag/7.2.0

See https://github.com/ui-router/visualizer#statevisualizernodelabel for example
