### ISSUE TITLE
7.2.0 seems to break apps in IE11

### ISSUE THREAD

**Issue by timhemendinger** [ui-router/visualizer#298]
Hi there, just a heads up... I updated to 7.2.0 and I was getting an error in the console for IE11 and the app wouldn't run--clicking on the error for the file brought me to the line in my screenshot below. There seems to be an arrow function that's not getting transpiled. 7.1.0 was doing the same so for the time being I've gone back to 7.0. 

![image](https://user-images.githubusercontent.com/4564786/93626539-30b24480-f9a9-11ea-9785-0968a4089353.png)

**Comment by christopherthielen** [comment]
Why are using IE11?
OK, thanks for letting me know.
Why are using IE11?
I changed the build from webpack to rollup, but didn't expect this to happen.
Why are using IE11?
I'll look into it.
Why are using IE11?


😄 😄

**Comment by timhemendinger** [comment]
I ask folks the same question every day, if it were up to me I wouldn't have rolled the version back :-D 

Thanks
