### ISSUE TITLE
What version of visualizer goes with angular-ur-router 1.0.0-rc.1?

### ISSUE THREAD

**Issue by ghost** [ui-router/visualizer#33]
Hi,
Is there any document regarding my question, where I could find and match proper visualizer version?
I just did `npm install --save @uirouter/visualizer` and got `npm WARN @uirouter/visualizer@4.0.2 requires a peer of @uirouter/core@>=5.0.0 but none was installed.` and I don't know what to do.

**Comment by christopherthielen** [comment]
The package `angular-ui-router` has been renamed.  You should remove it and instead install `@uirouter/angularjs` which is at version 1.0.11.  NPM should have warned you with a deprecation warning during install.  Did it?
