### ISSUE TITLE
When clicked State Visualizer dissapears

### ISSUE THREAD

**Issue by ghost** [ui-router/visualizer#34]
As said, and to get it back I have to reload page (SPA) so this misses the point....
Visualizer version: 3.1.3
UI Router version 1.0.0-rc.1
AngularJS version 1.6,5
TypeScript version 2.3.4
Browser:  Chrome  60.0.3112.90 (Official Build) (64-bit)

**Comment by christopherthielen** [comment]
Fixed in 5.0.5!

this bug was triggered when your "click-to-restore" dragged the window a teeny bit
