### ISSUE TITLE
update dependency preact to 8.2.xx

### ISSUE THREAD

**Issue by AnWeber** [ui-router/visualizer#35]
I am using latest visualizer with Typescript 2.4.2. In the build I get this error:
```
ERROR in ...\node_modules\@uirouter\visualizer\node_modules\preact\dist\preact.d.ts
(40,17): error TS2559: Type 'Component<PropsType, StateType>' has no propert
```
This error is already fixed in https://github.com/developit/preact/issues/735 and preact v8.2 is already released, but visualizer keeps installing v7.xx. 

Please update the depencency. Currently I am using a workaround and shinkwrap the version.

**Comment by trumbitta** [comment]
Still a problem.

Also, Angular 5 released yesterday uses Typescript 2.4.x

**Comment by elboman** [comment]
I'm not sure how this is still a problem as current `preact` version is 8.2.5: https://github.com/ui-router/visualizer/blob/master/package.json#L38

**Comment by trumbitta** [comment]
@elboman you're right, I just had to update `@uirouter/visualizer` to 5.0.0 - released a couple days ago :)

**Comment by elboman** [comment]
awesome, glad it's fixed 😄
