### ISSUE TITLE
[State tree] large app

### ISSUE THREAD

**Issue by aitboudad** [ui-router/visualizer#9]
Possible enhancements:
- use middle click to expand/collapse tree
- show only the first level

![selection_020](https://cloud.githubusercontent.com/assets/1753742/17643076/83620160-6156-11e6-8aff-d6ecd8f1cca3.png)

**Comment by christopherthielen** [comment]
What? it looks fine to me.  ;)

**Comment by christopherthielen** [comment]
The middle-click idea seems like pretty low-hanging fruit.  I don't have time to enhance this now, but would be happy to help guide anyone interested in implementing this.

**Comment by christopherthielen** [comment]
One other thing to note: you can increase the size of the viewport by passing `height` and `width` props to the third argument of `StateVisualizer.create`:

```js
  var vis = window['ui-router-visualizer']
  vis.StateVisualizer.create(ng1UIRouter, undefined, { width: 500, height: 500 });
  vis.TransitionVisualizer.create(ng1UIRouter);
```
https://plnkr.co/edit/dKT52b?p=preview

**Comment by aitboudad** [comment]
thank you for the hint, I'll try to work on it next week!

**Comment by wpitallo** [comment]
Awesome tool, very cool!

Was wandering how the labels are rendering? If we wanted to send them through a custom parser to add some addition info etc. What code actually renders the labels?

**Comment by christopherthielen** [comment]
Here is where the state node is written out (as SVG text): https://github.com/ui-router/visualizer/blob/master/src/state/stateNode.tsx#L33-L40

Just below it is the "label text" (i.e., "active")

The node itself is the `StateVisNode` which wraps a ui-router state object.

**Comment by wpitallo** [comment]
Thanks so much 👍 

Was exactly what i was looking for!

**Comment by christopherthielen** [comment]
I added some enhancements which makes the visualizer much more usable with large state trees:

1) Added other layout strategies:  Tree (current), Cluster, Radial.  The Radial layout works great for large apps.

<img width="490" alt="screen shot 2017-01-27 at 10 19 05 am" src="https://cloud.githubusercontent.com/assets/2053478/22378158/41acdf36-e47a-11e6-87f6-a23a43c313ed.png">

2) Add a zoom level which scales the state nodes and labels:

<img width="478" alt="screen shot 2017-01-27 at 10 19 19 am" src="https://cloud.githubusercontent.com/assets/2053478/22378177/4c9e1022-e47a-11e6-933a-97360730d420.png">

**Comment by christopherthielen** [comment]
4. Added Collapse/uncollapsing.

- Toggle collapse by double-clicking a state
- The count of collapsed descendents is shown inside the state
- The state is automatically un-collapsed if it is entered.
- States without children cannot be collapsed.


![anim](https://cloud.githubusercontent.com/assets/2053478/22398506/6da7639c-e54f-11e6-80b7-1fcd68269662.gif)

**Comment by christopherthielen** [comment]
@aitboudad  version 3.0.0 released, please provide feedback

**Comment by aitboudad** [comment]
@christopherthielen just checked on my side and it looks really nice, I have two remarks:
- allow to configure inactive state with children collapsed as default
- add horizontal tree (left to right)

Thanks in advance!

**Comment by christopherthielen** [comment]
@aitboudad just before registering the plugin you can set the initial collapsed status of each state.

For example:
```js
let states: State[] = router.stateRegistry.get().map(s => s.$$state());
let secondLevel = states.filter(s => s.parent.name === 'app');
secondLevel.forEach(s => s._collapsed = true);

router.plugin(Visualizer);
```

Or in this plunker, collapse all top and second level states:
http://plnkr.co/edit/zrc8YzoXnlhLbSD3TtWc?p=preview
```js
  // Auto-collapse children in state visualizer
  var registry = $uiRouter.stateRegistry;
  $uiRouter.stateRegistry.get().map(s => s.$$state())
      .filter(s => s.path.length === 2 || s.path.length === 3)
      .forEach(s => s._collapsed = true);
```
